[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_CONVEX_URL = "https://reserved-sailfish-472.convex.cloud"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_Z2VuZXJvdXMtcXVhZ2dhLTI4LmNsZXJrLmFjY291bnRzLmRldiQ"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyDeGH_ix4427x3-W3T-xzw2wfAgN8jeJ5c"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "shadow-heist.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_DATABASE_URL = "https://shadow-heist-default-rtdb.firebaseio.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "shadow-heist"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "shadow-heist.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "356686762351"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:356686762351:web:919531754d1c7c5af8989a"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-Y20TM7YBL0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 